#!/bin/sh
#----------------------------------------------------
# File:         .xinitrc
#----------------------------------------------------
# copy & mod of /etc/X11/xinit/xinitrc

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Begin my stuff
cd "$HOME" || exit 1

# Set correct $PATH for dmenu
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# Monitor s***
#xrandr --output eDP1 --mode 1920x1080 --left-of DP2-2 \
#    --output DP2-2 --primary --mode 1920x1200 \
#    --output DP2-3 --mode 1920x1200 --right-of DP2-2 --rotate left &
#xrandr --output eDP1 --mode 1920x1080

# unclutter -idle 4 &
#xset m 1 1 &

# pulseaudio control
pasystray &

# notification daemon
#    dunst \
#      -fn "Dejavu 12" \
#      -follow keyboard \
#      -format "<b>%s</b>\n\n%b" \
#      -geometry "300x5-30+20" \
#      -horizontal_padding 16 \
#      -markup \
#      -padding 18 \
#      -separator_height 1 \
#      -word_wrap &
# quickfix for start issue (see https://github.com/dunst-project/dunst/issues/347)
systemctl --user set-environment DISPLAY=:0
dunst &

# adjust light spectrum for better sleeping (disabled until flicker is
# resolved)
redshift &

# Automount removeable media
udiskie -t &

# Disable touchpad
# (configure somehow via libinput)
#synclient TouchpadOff=1

# keyboard stuff
#setxkbmap us altgr-intl
setxkbmap -option terminate:ctrl_alt_bksp &
(sleep 3 && xmodmap "${HOME}"/.Xmodmap) &

# clipboard syncing
clipmenud &

# visual stuff
xrdb -load "${HOME}"/.Xresources

# dropbox
#dropbox-cli start

# java programs should behave sane
wmname LG3D

# compositing
#compton --config "$HOME/.config/compton.conf" -b
picom &

# Network
nm-applet &

# Start up some Apps 
#keepassxc & 

# SSH Agent
#eval $(ssh-agent)
#ssh-add .ssh/id_rsa

# Gnome keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# Polkit agent (VIA & Co)
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# Monitor
#{ sleep 3; xrandr --output eDP-1 --mode 1920x1080 --left-of DP-2-2 \
#    --output DP-2-2 --primary --mode 1920x1200 \
#    --output DP-2-3 --mode 1920x1200 --right-of DP-2-2 --rotate left; } &

# At home
#{ sleep 3; xrandr --output HDMI-1 --primary --output DP-1 --left-of HDMI-1 --output eDP-1 --off; } &
#{ sleep 3; xrandr --output HDMI-0 --mode 2560x2880 --left-of DP-2 --primary --output DP-2 --right-of HDMI-0; } &
{ sleep 3; xrandr --output HDMI-0 --mode 2560x2880 --left-of DP-0 --output DP-0 --primary --output DP-2 --right-of DP-0; } &


# Office MUC
#{ sleep 3; xrandr --output HDMI-0 --primary --output DP-2 --left-of HDMI-0; } &
#{ sleep 3; xrandr --output HDMI-0 --primary --output DP-0.2 --left-of HDMI-0 --output DP-2 --left-of DP-0.2; } &
#{ sleep 3; xrandr --output DP-0.2 --output DP-0.1 --primary --right-of DP-0.2 --output DP-2 --left-of DP-0.2; } &


# KA
#{ sleep 3; xrandr --output DP-0.1.5 --primary --mode 3440x1440 --output DP-2 --left-of DP-0.1.5; } &

# Stuggi
#{ sleep 3; xrandr --output DP-0.3 --mode 1920x1080 --left-of DP-0.1 --output DP-0.1 --primary --mode 1920x1080 --output DP-2 --right-of DP-0.1; } &



# Single
#xrandr --output DP-2 --primary &

# wallpaper
{ sleep 3; sh "${HOME}"/.fehbg; } &

# i3
exec i3
