"----------------------------------------------------
" Author:       Max "keks" Fischer
"
" File:         .vimrc
"----------------------------------------------------

set nocompatible
call pathogen#infect()

" syntastic
set statusline+=%#warningmsg#
let g:syntastic_check_on_open = 1

" }}}
